### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by akien-mga** [vlabo/Godot_rope_addon#1]
You mentioned that the addon is under the MIT license on https://godotengine.org/asset-library/asset/edit/235, but it's not visible in the downloaded files.

Please add a LICENSE file with the license text, see https://choosealicense.com/

**Comment by vlabo** [comment]
Sorry for that. I just added the LICENSE file.

**Comment by akien-mga** [comment]
Fixed with 7b522a4.
